<?php


namespace app\base;


use app\components\RbacComponent;
use yii\base\Action;
use yii\web\Controller;

class BaseController extends Controller
{
    /**
     * @var RbacComponent
     */
    public $rbac;

    protected function getRbac(){
        return \Yii::$app->rbac;
    }

    /**
     * @param Action $action
     * @return bool|\yii\web\Response
     * @throws \yii\web\BadRequestHttpException
     */
    public function beforeAction($action)
    {
        if(\Yii::$app->user->isGuest){
            return $this->redirect('/auth/login');
        }
        return parent::beforeAction($action);
    }

//    /**
//     * @param Action $action
//     * @param mixed $result
//     * @return mixed
//     */
//    public function afterAction($action, $result)
//    {
//        $page = \Yii::$app->request->url; // так понятнее.
//        \Yii::$app->session->set('page_url',$page);
//        return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
//    }
}